name: Alpine 32-bit

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: i386/alpine
    steps:
      - name: install the Perl header, core modules, building tools
        run: |
          apk update
          apk add build-base perl perl-dev
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      #- name: perl %Config
      #  run: perl -MConfig -MData::Dumper -e 'local $Data::Dumper::Sortkeys = 1;warn Dumper \%Config;'
      - name: perl Makefile.PL
        run: perl Makefile.PL
        env: 
          BUILD_ZLIB: 0
      - name: make
        run: make
      - name: make test
        run: make test
