  freebsd:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@main
    - uses: vmactions/freebsd-vm@v0.1.6
      with:
        #prepare: pkg install -y p5-ExtUtils-PkgConfig
        run: |
            perl -V
            perl Makefile.PL
            make
            prove -wlvmb t
